# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180512_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='video/%Y/%m', verbose_name='封面'),
        ),
    ]
